###############################################################################
# Dependencies

GetSlopeFeatures <- function(raw.data.name="train",datasets=c("alsfrs","fvc","svc","vital","lab")) {
	
	# For a list of datasets generated by GetSlopeData, returns a dataset
  	# containing static features derived from slope data.
	#
	# Args: 
	# 	raw.data.name: name of dataset
	#	datasets: a vector with the names of datasets to get slope features for 
	#
	# Returns:
	#	A dataset in which for each row corresponds to a unique subject.id.  
	#	The columns consist of subject.id and features derived from slope data. 
	#
	# Example usage:
	#	  slope.features<-GetSlopeFeatures("train")

	data.name<-paste(sort(datasets),collapse='_')
	# Check to see if vital features datafile has been created, if so, load
	rda.filename = paste("Data/slope_",data.name,"_",
		raw.data.name,"_features.rda",sep="")
	
	if (file.exists(rda.filename)) {
		print(paste("loading saved slope features from",rda.filename,sep=" "))
		load(rda.filename)
		print("finished loading")
		return(slope.features)
	}

	# Get list of slope datasets, one per measure
	data.list<-GetSlopeData(raw.data.name,datasets)
	columns<-names(data.list)
		
	# Get a list of datasets containing feature data for each test	
  feature.list<-mapply(GetDefaultFeatures,raw.data.name,data.list,columns,
    SIMPLIFY=FALSE)

	# Add dataset containing all subject ids to beginning of feature list so all subject ids will be represented
	feature.list<-c(list(GetSubjectIds(raw.data.name)),feature.list)

	# Merge all datasets in the list by subject id 
	slope.features<-Reduce(function(x,y) {merge(x,y,by="subject.id",all.x=TRUE)},
		feature.list)
		
	# Save features data to RDA file
	save(slope.features, file = rda.filename)

	return(slope.features)

}






