################################################################################

SlopeTargets <- function(dataset) {
	# Gets the components of the slope calculation: the first score and 
  # first date after 3 months, and the first date and score after 12 months, or
  # if this data doesn't exist, the last date and score available
  #
	# Args:
	#	dataset: An ALSFRS dataset generated by GenAlsfrsData
	#
	# Returns: 
	#	  A dataset with the following columns:
  #     subject.id, first.date, first.score, last.date, and last.score
	#
	# Example usage:
	# 	slope.targets<-SlopeTargets(alsfrs.data)
	
	alsfrs.questions<-GetAlsfrsQuestions()
	# set all values for 5b to NA in rows where values for 5a and 5b are both 
	# numbers
	dataset$cutting.w.gastrostomy[!is.na(dataset$cutting.wo.gastrostomy)&!is.na(
		dataset$cutting.wo.gastrostomy)]<-NA
	sum<-rowSums(dataset[,colnames(dataset) %in% alsfrs.questions],
	na.rm=TRUE)
	cols<-colnames(dataset)
	dataset<-cbind(dataset,sum)
	colnames(dataset)<-c(cols,"alsfrs.score")
	return(dataset)
}
